// <auto-generated />
using ChatBridgeService.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ChatBridgeService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907000000_AddTwilioProvider")]
    partial class AddTwilioProvider
    {
    }
}
