// <auto-generated />
using ChatBridgeService.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ChatBridgeService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729120000_AddKirimDevConversations")]
    partial class AddKirimDevConversations
    {
    }
}
